name: 'release'
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.SPENDESK_BOT_SEMANTIC_RELEASE_ACCESS_TOKEN }}
  NODE_VERSION: 16.18.0

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: release action
        run: npx semantic-release
