name: 'release'
on: [push]
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN_RW }}
  GITHUB_TOKEN: ${{ secrets.SPENDESK_BOT_SEMANTIC_RELEASE_ACCESS_TOKEN }}
  NODE_VERSION: 14.16.0

jobs:
  build-release: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: release action
        uses: ./
        with:
          use-semantic-release: "false"